# Resumen de los datos: dimensiones y estructura

In [1]:
import pandas as pd
import os

In [7]:
mainpath = r"C:\Users\USER\OneDrive\Documentos\GitHub\python-ml-course"
filename = r"datasets\titanic\titanic3.csv"
fullpath = os.path.join(mainpath,filename)

In [8]:
data = pd.read_csv(fullpath)

In [16]:
data.tail()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [14]:
data.shape

(1309, 14)

In [19]:
# Para lectura de las columanas se usa el atributo .column
data.columns.values

<StringArray>
[   'pclass',  'survived',      'name',       'sex',       'age',     'sibsp',
     'parch',    'ticket',      'fare',     'cabin',  'embarked',      'boat',
      'body', 'home.dest']
Length: 14, dtype: str

Vamos a hacer un resumen de los estadisticos basicos de las variables numericas

In [20]:
data.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [21]:
data.dtypes

pclass         int64
survived       int64
name             str
sex              str
age          float64
sibsp          int64
parch          int64
ticket           str
fare         float64
cabin            str
embarked         str
boat             str
body         float64
home.dest        str
dtype: object